### ISSUE TITLE
No .jar file when attempting to download

### ISSUE THREAD

**Issue by CarterMane** [Sefiraat/Cultivation#45]
I wanted to download cultivation for my slimefun server, but the download link led me to an error screen, so I made an account to create an issue for this.

**Comment by Sefiraat** [comment]
> I wanted to download cultivation for my slimefun server, but the download link led me to an error screen, so I made an account to create an issue for this.

It’s not released yet :)
We’re still in the test-in-live stage on a handful of public Slimefun servers as a beta. 

You’re more than welcome to download the testing jar from the Slimefun Addon Community discord (https://discord.gg/wubrRAy4kv). You need to use the Channels-and-roles feature to sign up as a Guinea pig to see the cultivation testing channel
