### ISSUE TITLE
Seed pack not showing what seed is inside

### ISSUE THREAD

**Issue by CreeperJockeyJr** [Sefiraat/Cultivation#58]
step 1: store a seed type for your seed pack.
step 2: after exiting the seed pack interface you have no way of knowing what seed type it stores unless you open it.
In the seed pack item description it keeps saying set to: nothing
Video Proof:

https://user-images.githubusercontent.com/102436375/236365606-6812ac7a-0eee-4328-959a-715a6e19b84c.mp4

@Skizzles

**Comment by Sefiraat** [comment]
Oh forgot to link the PR - this has been fixed :)
