### ISSUE TITLE
Exotic Garden support.

### ISSUE THREAD

**Issue by MagmaBro123** [Sefiraat/Cultivation#59]
Title. This addon and Exotic Garden may contain some of the same foods/drinks/plants/recipes/etc.

**Comment by J3fftw1** [comment]
Yes it can have some of the same items.
What are you suggesting?

**Comment by MagmaBro123** [comment]
Replacing EG's kitchen multiblock with Cultivation's kitchen system, changing recipes, etc.

There's a lot of stuff EG compatibility could do.

**Comment by J3fftw1** [comment]
There is a lot that can be done. I certainly agree with that but you have not really given any suggestion.
We have come up with a lot of stuff to make this. You are now just saying. 
Add more stuff without giving an idea about what to add.
Im closing this issue. Please give a well written report on what you want added and what it should do then we could work of it.
