### ISSUE TITLE
Plants codex removed from GUI

### ISSUE THREAD

**Issue by SrMonsterYT** [Sefiraat/Cultivation#61]
I am able to get the item out of the GUI

image: https://prnt.sc/G09_CwERaGbk
image 2: https://prnt.sc/vl-R7QhM2Dps

Pufferfish git-Pufferfish-47 (MC: 1.19.2)
Slimefun DEV - 1050 (git 22a7f422)
Metrics-Module #28
Java 17

addon: Cultivation - DEV 9 (git df727).jar

no error console.

**Comment by Sefiraat** [comment]
Are you sure there are no errors? I cannot recreate this myself and normally you can only pull an item from a GUI when there is an error of some kind.

Also are you able to take a video of you pulling the item out? Ideally with the steps you took to do so

**Comment by Sefiraat** [comment]
Are you running spigot/paper 1.19.4? It ONLY works on 19.4+

**Comment by SrMonsterYT** [comment]
> Pufferfish git-Pufferfish-47 (MC: 1.19.2)

Pufferfish git-Pufferfish-47 (MC: 1.19.2)

ok thanks
