### ISSUE TITLE
wildstacker and Cultivation conflict

### ISSUE THREAD

**Issue by SrMonsterYT** [Sefiraat/Cultivation#67]
when we kill the salmon, guardian and squid nothing falls from them and still gives an error in the console

Pufferfish version git-Pufferfish-14 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 1e911fb on HEAD)

video: https://youtu.be/qiwRBQWiaw4
error console: https://prnt.sc/LG66XoSeAKfV

slimefun version and addons: https://prnt.sc/q52sfhmIMVaS

wildstacker said the problem is with slimefun not with him: https://prnt.sc/a-ZWqdgiqDUB

**Comment by Sefiraat** [comment]
In your last report you said this happened with GN_SALMON_ROE - I asked you what addon this was from, because I do not know - it's not part of cultivation?

**Comment by SrMonsterYT** [comment]
> In your last report I said this happened with GN_SALMON_ROE - I asked you what addon this was from, because I do not know - it's not part of cultivation?

I'm sorry, I think it's from Gastronomicon?

**Comment by Sefiraat** [comment]
Ah, that would make sense with GN_* - I didn't make that link. Fair enough, this can be close then, best raise on their repo
